name: kg-assistant
base: core18
version: '0.0.3'
summary: Assistant is a delightful files mod tool.
description: |
  * rename files in folder with index
  * sort for index - standard by name, natural by name, last modification file
  * search in folder files regex
  * size zeros in index
  * uppercase extension in folder
  * lowercase extension in folder

grade: stable
confinement: strict

parts:
  kgassistant:

    plugin: gradle
    gradle-output-dir: build/libs
    gradle-options: [jar]
    source: https://github.com/keygenqt/assistant.git
    source-type: git
    source-tag: master
    build-environment:
      - JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
      - PATH: $JAVA_HOME/jre/bin:$PATH

    build-packages:
      - openjdk-11-jdk
      - openjdk-11-jre

    stage-packages:
      - openjdk-11-jre

apps:
  kg-assistant:
    command: java -jar $SNAP/jar/assistant.jar
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
